[package]
name = "sol"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "3.0.3", default-features = false, features = ['std'] }
solana-sbpf = { path = "../../sbpf" }
bs58 = "0.5.1"
